# Generated by Django 5.2.1 on 2025-06-11 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supersetexercise',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workoutexercise',
            options={'ordering': ['weight'], 'verbose_name': 'Упражнение в тренировке', 'verbose_name_plural': 'Упражнения в тренировке'},
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='order',
        ),
    ]
