# Generated by Django 5.2.1 on 2025-06-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_workout_supersets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutsuperset',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='workoutsuperset',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workout',
            name='supersets',
            field=models.ManyToManyField(blank=True, related_name='workouts', through='api.WorkoutSuperSet', to='api.superset'),
        ),
        migrations.RemoveField(
            model_name='workoutsuperset',
            name='order',
        ),
    ]
