# Generated by Django 5.2.1 on 2025-06-18 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_workoutsuperset_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='location',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='start_time',
        ),
    ]
