# Generated by Django 5.2.1 on 2025-06-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_workout_end_time_remove_workout_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsuperset',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
