# Generated by Django 5.2.1 on 2025-06-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_workoutsuperset_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitamin',
            name='photo',
            field=models.ImageField(default=1, upload_to='vitamins/', verbose_name='Фотография'),
            preserve_default=False,
        ),
    ]
