# Generated by Django 5.2.1 on 2025-06-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_progressphoto_photo_progressphoto_photo_front_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishbodyresult',
            name='photo_front',
            field=models.ImageField(default=1, upload_to='wish/', verbose_name='Фотография'),
            preserve_default=False,
        ),
    ]
