# Generated by Django 5.2.1 on 2025-06-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_wishbodyresult_photo_front'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodymeasurement',
            name='buttock_left',
        ),
        migrations.RemoveField(
            model_name='bodymeasurement',
            name='buttock_right',
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='buttock',
            field=models.FloatField(default=1, verbose_name='Ягодицы, см'),
            preserve_default=False,
        ),
    ]
